package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	out := flag.String("out", "catalog_generated.go", "generated file path")
	flag.Parse()

	content := []byte(`// Code generated by go generate; DO NOT EDIT.

package catalog

const CatalogVersion = "demo-2026-05"
`)

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*out, content, 0o644); err != nil {
		panic(err)
	}

	fmt.Println("generated", *out)
}
